manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: kevinpastor
      url-base: https://github.com/kevinpastor
    - name: m165437
      url-base: https://github.com/M165437
    - name: s6t
      url-base: https://github.com/s6t
    - name: infely
      url-base: https://github.com/infely
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: hammerbeam-slideshow
      remote: gpeye
      revision: v0.3-branch
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: v0.3-branch
    - name: nice-view-elemental
      remote: kevinpastor
      revision: v0.3-branch
    - name: nice-view-gem
      remote: m165437
      revision: v0.3-branch
    - name: zmk-shield-nice-view-cats
      remote: s6t
      revision: v0.3-branch
    - name: nice-view-battery
      remote: infely
      revision: v0.3-branch
  self:
    path: config
